# Generated by Django 3.0.3 on 2020-05-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsinstructormatch',
            name='instructor_id',
        ),
    ]
