# Generated by Django 3.0.6 on 2020-05-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportcenter', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], max_length=6)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(max_length=10)),
                ('role', models.CharField(choices=[('MANAGER', 'manager'), ('INSTRUCTOR', 'instructor'), ('CUSTOMER', 'customer')], default='instructor', max_length=10)),
                ('sport_center_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.SportCenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
