# Generated by Django 3.0.3 on 2020-05-16 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('fba8a8da-e189-4c92-9532-750ed6e2f868'), editable=False, primary_key=True, serialize=False),
        ),
    ]
