# Generated by Django 3.0.6 on 2020-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0004_auto_20200601_1310'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='packages',
            field=models.ManyToManyField(through='sportcenter.CustomerPackage', to='sportcenter.Package'),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(through='sportcenter.InstructorService', to='sportcenter.Service'),
        ),
    ]
