# Generated by Django 3.0.3 on 2020-05-17 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200517_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('5788d728-d854-4e82-8299-b202704eca41'), editable=False, primary_key=True, serialize=False),
        ),
    ]
