# Generated by Django 3.0.6 on 2020-05-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200526_1305'),
        ('sportcenter', '0005_customerpackage_instructorservice_packageservice'),
        ('accounts', '0003_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sport_center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.SportCenter'),
        ),
    ]
