# Generated by Django 3.0.6 on 2020-05-22 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200517_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('d517507a-08bd-4239-a1b2-41a67368182c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
