# Generated by Django 3.0.3 on 2020-05-24 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsinstructormatch_instructor_id'),
        ('accounts', '0006_auto_20200522_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'manager'), ('INSTRUCTOR', 'instructor'), ('CUSTOMER', 'customer')], default='instructor', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('86e90664-b0c0-456f-97ee-cc8ee6c5ccab'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
