# Generated by Django 3.0.3 on 2020-05-24 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200524_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('4067910a-785d-4a7f-b037-b3e2116f6f74'), editable=False, primary_key=True, serialize=False),
        ),
    ]
