# Generated by Django 3.0.3 on 2020-05-24 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200524_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('42840ce8-ba50-4093-ab11-58f125eb224f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
