# Generated by Django 3.0.3 on 2020-05-24 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200524_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('9013cc54-664a-462e-9e9e-3ff08c1ef21b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
