# Generated by Django 3.0.3 on 2020-05-24 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200524_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'manager'), ('INSTRUCTOR', 'instructor'), ('CUSTOMER', 'customer')], default='instructor', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('8df3e738-66eb-4501-90b4-476f7fe7bdd3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
