# Generated by Django 3.0.3 on 2020-05-24 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200524_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('8fb248c6-ad87-4f50-8a0e-6c23833d48a0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
