# Generated by Django 3.0.3 on 2020-05-24 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200524_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('01037c48-8b3b-41ba-8c76-f054d473091d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
