# Generated by Django 3.0.6 on 2020-05-22 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportCenter',
            fields=[
                ('sport_center_id', models.UUIDField(default=uuid.UUID('d34f8baa-700d-4def-bd5b-07252eece209'), editable=False, primary_key=True, serialize=False)),
                ('sport_center_name', models.CharField(max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
