# Generated by Django 3.0.6 on 2020-06-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('address', '0002_auto_20200526_1305'),
        ('sportcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sport_center_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.SportCenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sport_center_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.SportCenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='room_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='service_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportcenter',
            name='address_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
            preserve_default=False,
        ),
    ]
