# Generated by Django 3.0.6 on 2020-05-22 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.UUIDField(default=uuid.UUID('cdba417f-0922-428c-9d6d-70ac79ea2cd2'), editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.UUID('29fd3b4d-4d56-4901-91fd-f10932445a71'), editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.UUID('07f3ba97-8b26-44ed-a0c5-f2239790727f'), editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.UUID('2acd33fd-c426-44d8-867d-16de0fad3652'), editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sportcenter',
            name='sport_center_id',
            field=models.UUIDField(default=uuid.UUID('4c0f90d0-ee90-4eea-964b-324856fe1b33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
