# Generated by Django 3.0.6 on 2020-05-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200528_1738'),
        ('sportcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Package')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Package')),
            ],
        ),
    ]
