# Generated by Django 3.0.3 on 2020-05-24 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0002_auto_20200522_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('7d596336-c01b-4784-9c25-da86a290105f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('d5682680-c5b0-48c4-a4d6-1c81aef36541'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.UUIDField(default=uuid.UUID('a3b9e63c-98ac-45f7-9fff-6a6f3657a4eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.UUIDField(default=uuid.UUID('8e8b1370-cafc-42bc-8093-efe4b59eb7f6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sportcenter',
            name='sport_center_id',
            field=models.UUIDField(default=uuid.UUID('abea02d0-57d2-4dcc-a79c-006074eb22ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
