# Generated by Django 3.0.6 on 2020-06-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0002_auto_20200601_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Package')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(through='sportcenter.PackageService', to='sportcenter.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='packages',
            field=models.ManyToManyField(through='sportcenter.PackageService', to='sportcenter.Package'),
        ),
    ]
