# Generated by Django 3.0.6 on 2020-05-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0002_sportcenter_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sport_center_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.SportCenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sport_center_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.SportCenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='room_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='service_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service'),
            preserve_default=False,
        ),
    ]
