# Generated by Django 3.0.3 on 2020-05-24 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0003_auto_20200524_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('2601caea-ad6a-4bd3-a6c0-92c2a5ed9a25'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('ed1de7d5-c1db-4940-8355-96aa7769841e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.UUIDField(default=uuid.UUID('c02d2fc9-fd65-49fa-a3b9-a4db06ab6afb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.UUIDField(default=uuid.UUID('a880cdd3-daf2-4a03-8cd2-e3452bdc86fe'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sportcenter',
            name='sport_center_id',
            field=models.UUIDField(default=uuid.UUID('9aba1152-f710-4096-adc6-2ef2d71a8e35'), editable=False, primary_key=True, serialize=False),
        ),
    ]
