# Generated by Django 3.0.6 on 2020-05-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_id'),
        ('sportcenter', '0003_auto_20200526_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
            preserve_default=False,
        ),
    ]
