# Generated by Django 3.0.6 on 2020-06-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sportcenter', '0003_auto_20200601_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='customers',
            field=models.ManyToManyField(through='sportcenter.CustomerPackage', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='service',
            name='instructors',
            field=models.ManyToManyField(through='sportcenter.InstructorService', to='accounts.User'),
        ),
    ]
