# Generated by Django 3.0.6 on 2020-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenter', '0004_auto_20200601_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
