# Generated by Django 3.0.6 on 2020-05-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_id'),
        ('sportcenter', '0004_section_instructor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Package')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportcenter.Package')),
            ],
        ),
    ]
